title: [JJ Svenson's Baseball Analytics](https://jjsvenson.github.io/jj-svenson-baseball-analytics/)
description: "Showcasing my baseball analytics projects."
theme: jekyll-theme-minimal
url: "https://jj-svenson.github.io"
baseurl: "/jj-svenson-baseball-analytics"
