title: "JJ Svenson's Baseball Analytics"
description: "Showcasing my baseball analytics projects."
theme: jekyll-theme-minimal
url: "https://jjsvenson.github.io"
baseurl: "/jj-svenson-baseball-analytics"
