title: [JJ Svenson Baseball Analytics](index.md)
description: "Showcasing my baseball analytics projects."
theme: jekyll-theme-minimal
url: "https://jj-svenson.github.io"
baseurl: "/jj-svenson-baseball-analytics"
